source 'https://rubygems.org'

gem 'rails'
gem 'bcrypt-ruby' # probably possible to remove it

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pry'
gem 'rails-pry'

gem 'sqlite3'
gem 'mysql2'

gem 'haml'
gem 'twitter-bootstrap-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
group :production do
  gem 'unicorn'
end

# Deploy with Capistrano
# gem 'capistrano'

group :development do
  # To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
  # gem 'ruby-debug'
  #gem 'ruby-debug19'
  gem 'sqlite3'
  gem 'pry'
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
  #gem 'meta_request'
end


gem 'less-rails'
gem 'devise'
gem 'sentient_user'
gem 'kaminari'
gem 'cancan'
gem 'friendly_id'
gem 'carrierwave' # https://github.com/jnicklas/carrierwave
gem 'rmagick'
gem "nested_form", :git => "git://github.com/ryanb/nested_form.git"
gem "rails_config" # https://github.com/railsjedi/rails_config

gem 'libv8', '~> 3.11.8'
gem 'therubyracer'
